export const ADD_PROJECT = 'ADD_PROJECT';
export const PROJECT_LOADING = 'PROJECT_LOADING';
export const PROJECT_FAILED = 'PROJECT_FAILED';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';
export const ADD_BACKLOG = 'ADD_BACKLOG';
export const ADD_SPRINT = 'ADD_SPRINT';
export const ADD_FINAL_DOCUMENTATION = 'ADD_FINAL_DOCUMENTATION';
export const ADD_SUPERVISOR_MEETINGS = 'ADD_SUPERVISOR_MEETINGS';